In [1]:
import pandas as pd
import numpy as np

health_df = pd.DataFrame({
    "patient_id": [101,102,103,104,105,101,102,103,104,105,106,107,108,109],
    "patient_name": ["Alice","Bob","Charlie","Diana","Eve","Alice","Bob","Charlie","Diana","Eve","Frank","Grace","Hank","Ivy"],
    "age": [34, 45, 29, 50, 38, 34, 45, 29, 50, 38, 60, 42, 31, 27],
    "gender": ["F","M","M","F","F","F","M","M","F","F","M","F","M","F"],
    "visit_date": pd.to_datetime([
        "2024-03-01","2024-03-02","2024-03-02","2024-03-03","2024-03-04",
        "2024-03-10","2024-03-11","2024-03-11","2024-03-12","2024-03-12",
        "2024-03-15","2024-03-15","2024-03-16","2024-03-16"
    ]),
    "systolic_bp": [120, 140, 130, 150, 135, 125, 138, 128, 148, 132, 160, 145, 118, np.nan],
    "diastolic_bp": [80, 90, 85, 95, 88, 82, 87, 83, 92, 86, 100, 94, 77, 80],
    "heart_rate": [72, 88, 76, 95, 80, 74, 85, 78, 90, 82, 98, 89, 70, 75],
    "cholesterol_mg_dl": [190, 220, 180, 240, 210, 185, 215, 175, 235, 205, 250, 225, 170, 180],
    "diagnosis": ["Healthy","Hypertension","Healthy","Hypertension","Prehypertension",
                  "Healthy","Hypertension","Healthy","Hypertension","Prehypertension",
                  "Hypertension","Prehypertension","Healthy","Healthy"]
})

# Introduce some duplicates for realism
health_df = pd.concat([health_df, health_df.iloc[[1,4]]], ignore_index=True)
health_df

,patient_id,patient_name,age,gender,visit_date,systolic_bp,diastolic_bp,heart_rate,cholesterol_mg_dl,diagnosis
0,101,Alice,34,F,2024-03-01,120.0,80,72,190,Healthy
1,102,Bob,45,M,2024-03-02,140.0,90,88,220,Hypertension
2,103,Charlie,29,M,2024-03-02,130.0,85,76,180,Healthy
3,104,Diana,50,F,2024-03-03,150.0,95,95,240,Hypertension
4,105,Eve,38,F,2024-03-04,135.0,88,80,210,Prehypertension
5,101,Alice,34,F,2024-03-10,125.0,82,74,185,Healthy
6,102,Bob,45,M,2024-03-11,138.0,87,85,215,Hypertension
7,103,Charlie,29,M,2024-03-11,128.0,83,78,175,Healthy
8,104,Diana,50,F,2024-03-12,148.0,92,90,235,Hypertension
9,105,Eve,38,F,2024-03-12,132.0,86,82,205,Prehypertension
10,106,Frank,60,M,2024-03-15,160.0,100,98,250,Hypertension
11,107,Grace,42,F,2024-03-15,145.0,94,89,225,Prehypertension
12,108,Hank,31,M,2024-03-16,118.0,77,70,170,Healthy
13,109,Ivy,27,F,2024-03-16,NaN,80,75,180,Healthy
14,102,Bob,45,M,2024-03-02,140.0,90,88,220,Hypertension
15,105,Eve,38,F,2024-03-04,135.0,88,80,210,Prehypertension

In [2]:
'''
Task 1 - Clean data
'''

df_cleaned = (
    health_df
    .drop_duplicates()
    .assign(systolic_bp = lambda x: x.systolic_bp.fillna(x.systolic_bp.median()))
)
df_cleaned

,patient_id,patient_name,age,gender,visit_date,systolic_bp,diastolic_bp,heart_rate,cholesterol_mg_dl,diagnosis
0,101,Alice,34,F,2024-03-01,120.0,80,72,190,Healthy
1,102,Bob,45,M,2024-03-02,140.0,90,88,220,Hypertension
2,103,Charlie,29,M,2024-03-02,130.0,85,76,180,Healthy
3,104,Diana,50,F,2024-03-03,150.0,95,95,240,Hypertension
4,105,Eve,38,F,2024-03-04,135.0,88,80,210,Prehypertension
5,101,Alice,34,F,2024-03-10,125.0,82,74,185,Healthy
6,102,Bob,45,M,2024-03-11,138.0,87,85,215,Hypertension
7,103,Charlie,29,M,2024-03-11,128.0,83,78,175,Healthy
8,104,Diana,50,F,2024-03-12,148.0,92,90,235,Hypertension
9,105,Eve,38,F,2024-03-12,132.0,86,82,205,Prehypertension
10,106,Frank,60,M,2024-03-15,160.0,100,98,250,Hypertension
11,107,Grace,42,F,2024-03-15,145.0,94,89,225,Prehypertension
12,108,Hank,31,M,2024-03-16,118.0,77,70,170,Healthy
13,109,Ivy,27,F,2024-03-16,135.0,80,75,180,Healthy

In [3]:
'''
Task 2 - Compute new metrics
'''
def calculate_bp_category(systolic_bp_value):
    if systolic_bp_value < 120:
        return "Normal"
    elif systolic_bp_value < 140:
        return "Prehypertension"
    else:
        return "Hypertension"

df_metrics = (
    df_cleaned
    .assign(mean_arterial_pressure = (2*df_cleaned.diastolic_bp + df_cleaned.systolic_bp)/3)
    .assign(bp_category = lambda x: x.systolic_bp.apply(lambda y: calculate_bp_category(y)))
)
df_metrics

,patient_id,patient_name,age,gender,visit_date,systolic_bp,diastolic_bp,heart_rate,cholesterol_mg_dl,diagnosis,mean_arterial_pressure,bp_category
0,101,Alice,34,F,2024-03-01,120.0,80,72,190,Healthy,93.333333,Prehypertension
1,102,Bob,45,M,2024-03-02,140.0,90,88,220,Hypertension,106.666667,Hypertension
2,103,Charlie,29,M,2024-03-02,130.0,85,76,180,Healthy,100.000000,Prehypertension
3,104,Diana,50,F,2024-03-03,150.0,95,95,240,Hypertension,113.333333,Hypertension
4,105,Eve,38,F,2024-03-04,135.0,88,80,210,Prehypertension,103.666667,Prehypertension
5,101,Alice,34,F,2024-03-10,125.0,82,74,185,Healthy,96.333333,Prehypertension
6,102,Bob,45,M,2024-03-11,138.0,87,85,215,Hypertension,104.000000,Prehypertension
7,103,Charlie,29,M,2024-03-11,128.0,83,78,175,Healthy,98.000000,Prehypertension
8,104,Diana,50,F,2024-03-12,148.0,92,90,235,Hypertension,110.666667,Hypertension
9,105,Eve,38,F,2024-03-12,132.0,86,82,205,Prehypertension,101.333333,Prehypertension
10,106,Frank,60,M,2024-03-15,160.0,100,98,250,Hypertension,120.000000,Hypertension
11,107,Grace,42,F,2024-03-15,145.0,94,89,225,Prehypertension,111.000000,Hypertension
12,108,Hank,31,M,2024-03-16,118.0,77,70,170,Healthy,90.666667,Normal
13,109,Ivy,27,F,2024-03-16,135.0,80,75,180,Healthy,98.333333,Prehypertension

In [4]:
'''
Task 3 - Latest Visit per Patient
'''
df_patient_latest_visit = (
    df_metrics
    .loc[df_metrics.groupby('patient_id')['visit_date'].idxmax()][['patient_id','visit_date','diagnosis','mean_arterial_pressure']]
)
df_patient_latest_visit

    patient_id visit_date        diagnosis  mean_arterial_pressure
5          101 2024-03-10          Healthy               96.333333
6          102 2024-03-11     Hypertension              104.000000
7          103 2024-03-11          Healthy               98.000000
8          104 2024-03-12     Hypertension              110.666667
9          105 2024-03-12  Prehypertension              101.333333
10         106 2024-03-15     Hypertension              120.000000
11         107 2024-03-15  Prehypertension              111.000000
12         108 2024-03-16          Healthy               90.666667
13         109 2024-03-16          Healthy               98.333333

In [5]:
'''
Task 4 - Gender-based analysis
'''
df_gender_analysis = (
    df_cleaned
    .groupby('gender')
    .agg(
        avg_systolic_bp = ('systolic_bp','mean'),
        avg_diastolic_bp = ('diastolic_bp','mean'),
        avg_heart_rate = ('heart_rate','mean'),
        number_of_visits = ('patient_id','count')
    )
)
df_gender_analysis

        avg_systolic_bp  avg_diastolic_bp  avg_heart_rate  number_of_visits
gender
F            136.250000            87.125          82.125                 8
M            135.666667            87.000          82.500                 6

In [6]:
'''
Task 5 - High risk patients
'''
df_high_risk_patients = (
    df_cleaned
    .loc[(df_cleaned.systolic_bp >=140) & (df_cleaned.cholesterol_mg_dl >=230)]
    .sort_values('systolic_bp',ascending=False)
)
df_high_risk_patients

,patient_id,patient_name,age,gender,visit_date,systolic_bp,diastolic_bp,heart_rate,cholesterol_mg_dl,diagnosis
10,106,Frank,60,M,2024-03-15,160.0,100,98,250,Hypertension
3,104,Diana,50,F,2024-03-03,150.0,95,95,240,Hypertension
8,104,Diana,50,F,2024-03-12,148.0,92,90,235,Hypertension

In [7]:
'''
Task 6 - Time based analysis
'''
df_time_analysis = (
    df_cleaned
    .groupby(pd.Grouper(key='visit_date', freq='W'))['heart_rate']
    .mean()
    .to_frame()
)
df_time_analysis

            heart_rate
visit_date
2024-03-03      82.750
2024-03-10      77.000
2024-03-17      83.375