In [1]:
import pandas as pd

df = pd.DataFrame({
    "order_id":[1,2,3,4,5,6,7,8,9,10],
    "customer":["Alice","Bob","Alice","Diana","Charlie","Bob","Alice","Charlie","Diana","Bob"],
    "city":["London","Paris","London","Berlin","Paris","London","Berlin","Paris","London","Berlin"],
    "product":["Laptop","Phone","Tablet","Laptop","Tablet","Phone","Monitor","Laptop","Phone","Monitor"],
    "category":["Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics"],
    "price":[1200,800,600,1200,600,800,300,1200,800,300],
    "quantity":[1,2,1,1,3,1,2,1,1,4],
    "date":pd.to_datetime([
        "2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05",
        "2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10"
    ])
})
df

   order_id customer    city  product     category  price  quantity       date
0         1    Alice  London   Laptop  Electronics   1200         1 2024-01-01
1         2      Bob   Paris    Phone  Electronics    800         2 2024-01-02
2         3    Alice  London   Tablet  Electronics    600         1 2024-01-03
3         4    Diana  Berlin   Laptop  Electronics   1200         1 2024-01-04
4         5  Charlie   Paris   Tablet  Electronics    600         3 2024-01-05
5         6      Bob  London    Phone  Electronics    800         1 2024-01-06
6         7    Alice  Berlin  Monitor  Electronics    300         2 2024-01-07
7         8  Charlie   Paris   Laptop  Electronics   1200         1 2024-01-08
8         9    Diana  London    Phone  Electronics    800         1 2024-01-09
9        10      Bob  Berlin  Monitor  Electronics    300         4 2024-01-10

In [2]:
'''
Task 1 - Revenue per order
'''

df_chained = (
    df.assign(revenue = df.price * df.quantity)[['order_id','customer','revenue']]
    .sort_values('revenue',ascending=False)
)
df_chained

   order_id customer  revenue
4         5  Charlie     1800
1         2      Bob     1600
0         1    Alice     1200
3         4    Diana     1200
9        10      Bob     1200
7         8  Charlie     1200
8         9    Diana      800
5         6      Bob      800
2         3    Alice      600
6         7    Alice      600

In [3]:
'''
Task 2 - Total revenue per customer
'''
df_chained = (
    df.assign(revenue = df.price * df.quantity)
    .groupby('customer')
    .agg(total_revenue=('revenue','sum'))
    .sort_values('total_revenue',ascending=False)
)
df_chained

          total_revenue
customer
Bob                3600
Charlie            3000
Alice              2400
Diana              2000

In [4]:
'''
Task 3 - City sales analysis
'''
df_chained = (
    df.assign(revenue = df.price * df.quantity)
    .groupby('city')
    .agg(total_revenue = ('revenue','sum'),
         total_quanitiy_sold = ('quantity','sum'))
    .sort_values('total_revenue',ascending=False)
)
df_chained

        total_revenue  total_quanitiy_sold
city
Paris            4600                    6
London           3400                    4
Berlin           3000                    7

In [5]:
'''
Task 4 - High value orders
'''
df_chained = (
    df.assign(revenue = df.price * df.quantity)
    .loc[lambda row: row['revenue'] > 1000][['customer','product','revenue']]
    .sort_values('revenue',ascending=False)
)
df_chained

  customer  product  revenue
4  Charlie   Tablet     1800
1      Bob    Phone     1600
0    Alice   Laptop     1200
3    Diana   Laptop     1200
7  Charlie   Laptop     1200
9      Bob  Monitor     1200

In [6]:
'''
Task 5 - Most popular product
'''
df_chained = (
    df.groupby('product')
    .agg(quantities_sold=('quantity','sum'))
    .sort_values('quantities_sold',ascending=False)
    .idxmax()
)
df_chained

quantities_sold    Monitor
dtype: str

In [7]:
'''
Task 6 - customer purchase frequency
'''
df_chained = (
    df.groupby('customer')
    .agg(number_of_orders=('order_id','count'))
    .sort_values('number_of_orders',ascending=False)
)
df_chained

          number_of_orders
customer
Alice                    3
Bob                      3
Charlie                  2
Diana                    2

In [8]:
'''
Task 7 - daily revenue
'''
df_chained = (
    df.assign(revenue = df.price * df.quantity)
    .groupby('date')
    .agg(revenue_per_day=('revenue','sum'))
    .sort_values('date',ascending=False)
)
df_chained

            revenue_per_day
date
2024-01-10             1200
2024-01-09              800
2024-01-08             1200
2024-01-07              600
2024-01-06              800
2024-01-05             1800
2024-01-04             1200
2024-01-03              600
2024-01-02             1600
2024-01-01             1200